import type {NextPage} from 'next'
import Image from 'next/image'
import Meta from "../components/utility/Meta";
import Footer from "../components/shared/Footer/Footer";

const Home: NextPage = () => {
    return (
        <div className="h-screen bg-white">
            <Meta
                title={"ZNK App"}
                description={"Generated by create next app"}
                favicon
            />

            <main className="">
                ZNK App index page
            </main>

            <Footer/>
        </div>
    )
}

export default Home
